-- ============================================
-- RECEIPTS STORAGE BUCKET SETUP (MANUAL)
-- ============================================
-- IMPORTANT: This migration is a placeholder/documentation.
-- Buckets and storage policies require special permissions and must be created manually.
--
-- INSTRUCTIONS:
-- 1. Create bucket manually in Supabase Dashboard:
--    - Go to Storage > Create bucket
--    - Name: "receipts"
--    - Public: false (private)
--    - File size limit: 10MB
--    - Allowed MIME types: application/pdf, image/jpeg, image/png
--
-- 2. Create storage policies manually in Supabase Dashboard:
--    - Go to Storage > receipts bucket > Policies
--    - Create the following policies (or run the SQL below in SQL Editor):
--
--    Policy 1: "Users can upload own receipts"
--      Operation: INSERT
--      Target roles: authenticated
--      Policy: (bucket_id = 'receipts'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])
--
--    Policy 2: "Users can view own receipts"
--      Operation: SELECT
--      Target roles: authenticated
--      Policy: (bucket_id = 'receipts'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])
--
--    Policy 3: "Users can delete own receipts"
--      Operation: DELETE
--      Target roles: authenticated
--      Policy: (bucket_id = 'receipts'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])
--
--    Policy 4: "Users can update own receipts"
--      Operation: UPDATE
--      Target roles: authenticated
--      Policy: (bucket_id = 'receipts'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])
--
-- ALTERNATIVE: If you have permissions, you can run this SQL in SQL Editor (after creating the bucket):
--
-- DROP POLICY IF EXISTS "Users can upload own receipts" ON storage.objects;
-- CREATE POLICY "Users can upload own receipts" ON storage.objects
--   FOR INSERT TO authenticated
--   WITH CHECK (bucket_id = 'receipts' AND (auth.uid())::text = (storage.foldername(name))[1]);
--
-- DROP POLICY IF EXISTS "Users can view own receipts" ON storage.objects;
-- CREATE POLICY "Users can view own receipts" ON storage.objects
--   FOR SELECT TO authenticated
--   USING (bucket_id = 'receipts' AND (auth.uid())::text = (storage.foldername(name))[1]);
--
-- DROP POLICY IF EXISTS "Users can delete own receipts" ON storage.objects;
-- CREATE POLICY "Users can delete own receipts" ON storage.objects
--   FOR DELETE TO authenticated
--   USING (bucket_id = 'receipts' AND (auth.uid())::text = (storage.foldername(name))[1]);
--
-- DROP POLICY IF EXISTS "Users can update own receipts" ON storage.objects;
-- CREATE POLICY "Users can update own receipts" ON storage.objects
--   FOR UPDATE TO authenticated
--   USING (bucket_id = 'receipts' AND (auth.uid())::text = (storage.foldername(name))[1])
--   WITH CHECK (bucket_id = 'receipts' AND (auth.uid())::text = (storage.foldername(name))[1]);
--
-- This migration does nothing (placeholder only) to avoid permission errors.
